### ISSUE TITLE
Expired SSL certificate (api.ipify.org)

### ISSUE THREAD

**Issue by nightah** [rdegges/ipify-api#12]
Firstly apologies if this is not the right place to report this issue. I figured the alternative would be either to tweet or email you and out of these three options, this seemed most appropriate.

It seems the SSL certificate for api.ipify.org has expired today, 21/11/2016.

**Comment by einthusan** [comment]
Wow.. you beat me to it @nightah by 24 mins!

**Comment by shaunbrady** [comment]
This.  This is used by Ansible as a default.

**Comment by rdegges** [comment]
Working on this now. Ran into some issues.

**Comment by rdegges** [comment]
The new SSL cert is on the way -- waiting for comodo :(

**Comment by rdegges** [comment]
For some reason, my SSL renewal notifications apparently went into spam folder. Sorry everyone. Should be back to normal shortly.

**Comment by rdegges** [comment]
Everything is back up and running. Thanks folks!

**Comment by benyanke** [comment]
Have you considered Let's encrypt with autorenew? That's one of it's best features, frankly.

**Comment by rdegges** [comment]
Yeah! The only issue is integrating the cert stuff w/ Heroku properly. I'd have to write some custom stuff, just haven't gotten around to it yet. With my AWS stuff, it's not a big deal because I use ACM which does autorenew. But with the Heroku services, there isn't a clear integration yet.
