### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by BMillsVT** [rdegges/ipify-api#14]
Would you consider dual-licensing this under the MIT and Unlicense?  My company tries to steer clear of the Unlicense.

**Comment by rdegges** [comment]
Sorry, no :( I see no reason to make the project have stricter rules since right now it as absolutely free as possible.

**Comment by BMillsVT** [comment]
Thanks for the quick response.  I understand your point of view, but others have argued (and our lawyers at least agree enough to make it off limits) that the Unlicense causes more issues than it solves.  

[For example:](http://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense):
 

> **It's not global**. It doesn't make sense outside of a commonwealth ecosystem, is explicitly illegal in some places (Germany), and of unclear legality in others (Australia)
> 
> **It's inconsistent.** Some of the warranty terms cannot, logically, co-exist, given the current legal ecosystem, as written, with the licensing terms.
> 
> **Its applicability is unpredictable.** The license is short, clearly expressing intent, at the cost of not carefully addressing common license, copy-right and warranty issues. It leaves a lot of leeway interpretation - meaning that, in the US, it will take a few trials before you can reliably know when the license is applicable, and how.


Would you consider using the CC0 license?  Apparently that's "better" at being a public domain dedication since it has a better fall back clause. We'd really like to use your code.

**Comment by rdegges** [comment]
Sorry for the delay, I wasn't aware of this (just read through that SO link, pretty interesting...).

I think I have a better understanding now. What I did was added the MIT license to the project as well. This should meet your requirements =)

**Comment by BMillsVT** [comment]
That's awesome.  Thanks!  

Also, if you're interested the OSI has some FAQs about public domain dedications.  You know, if you're interested in a little more light reading. (https://opensource.org/faq#public-domain)

**Comment by rdegges** [comment]
Thank you =)
