### ISSUE TITLE
Change Python Example to Python 2/3

### ISSUE THREAD

**Issue by Miserlou** [rdegges/ipify-api#15]
Might as well change 

```python
print 'My public IP address is:', ip
```
to
```python
print('My public IP address is:', ip)
```
RIP `print`
:-(

**Comment by rdegges** [comment]
Hah, good call! Will do this.

Also: long time no see, buddy! <3 How is life?

**Comment by rdegges** [comment]
Anddd... Updated. Just waiting for cloudfront cache to clear =x

**Comment by Miserlou** [comment]
Hey man! Life's good! Hacking and traveling, you know how it goes! How are you?!

Your solution is better than mine!

**Comment by rdegges** [comment]
I'm doing good! Just been busy, hah. Still doing security / crypto work @ stormpath. Still up in the bay area, etc. You ever in bay area now-a-days? If so, we should hang sometime!

**Comment by Miserlou** [comment]
I'm currently a full-time nomad, been doing lots of travelling and talking lately related to [Zappa](https://github.com/Miserlou/Zappa). Just got back from [speaking at CCC](https://media.ccc.de/v/33c3-7865-gone_in_60_milliseconds) in Hamburg! So that was fun.

I hope I'll be back in the bay soon to escape the miserable east coast winter - I'll hit you up when I'm in town!

**Comment by rdegges** [comment]
That's awesome! Hit me up when you're in town =D
