### ISSUE TITLE
ipify.org domain blocked due to being reported as malware related

### ISSUE THREAD

**Issue by chrisma** [rdegges/ipify-api#2]
First off, thanks for providing this service!

Unfortunately it seems that Bitdefender anti-virus has listed the domain ipify.org as serving malware.
This may be because some malware authors have used the ipify.org service in their executable, see: https://malwr.com/analysis/NDY2YWRkOGU3MTAzNGVkNDgwNmVmMzQwZGI5ODVkNTE/
This occurs with the lastest version of Bitdefender (1.0.21.1099).

![screenshot_ipify](https://cloud.githubusercontent.com/assets/1652117/5617164/f5955cd2-950b-11e4-893b-4dff88ba7062.png)

**Comment by rdegges** [comment]
Thanks for the report! That's really annoying :( I'm trying to get in contact with them now. I couldn't see any easy way, so I tweeted them. Will update this issue as I hear back =)

**Comment by chrisma** [comment]
Hi,
thanks for the fast reply!
Unfortunately it seems that Bitdefender is not the root of the problem.
The domain api.ipify.org has made it onto the [Malware Domain Blocklist](http://www.malwaredomains.com/?page_id=66) (which is e.g. used per default by [µBlock](https://chrome.google.com/webstore/detail/%C2%B5block/cjpalhdlnbpafiamejdnhcphjbkeiagm))
![ipify](https://cloud.githubusercontent.com/assets/1652117/5645664/0194b4fc-9673-11e4-9c71-3877d2c53cc4.png)

**Comment by rdegges** [comment]
Just talked to bitdefender -- I submitted the URL to them. They're reviewing it and will remove it soon I hope. I'll also try to contact the malware domain blocklist.

**Comment by rdegges** [comment]
Here's bitdefender's email:

![screenshot 2015-01-07 23 16 41](https://cloud.githubusercontent.com/assets/90247/5659213/49f35280-96c3-11e4-8652-50451cab24f1.png)

I also just emailed the malware guys about getting it removed from there -- will update when I hear back.

**Comment by rdegges** [comment]
Haven't heard anything back, but since this stuff is out of my control anyhow: closing the issue.

**Comment by chrisma** [comment]
It seems your efforts were not in vain though :)
The [current Malware Domain Blocklist](http://mirror1.malwaredomains.com/files/domains.txt) does not seem to list `api.ipify.org` anymore

![selection_004](https://cloud.githubusercontent.com/assets/1652117/7533996/79049c5c-f576-11e4-986c-a996624f62c4.png)

**Comment by rdegges** [comment]
yey!

**Comment by tomg555** [comment]
[hpHosts ](https://hosts-file.net) by Malwarebytes still lists api.ipify.org in their malware list (EMD)

https://hosts-file.net/emd.txt

![image](https://user-images.githubusercontent.com/695445/33057424-8433f91e-ce50-11e7-9cce-b9e9318b40e1.png)

List classifications: https://hosts-file.net/?s=classifications

**Comment by rdegges** [comment]
Bummer! It's so annoying that providers falsely misclassiffy a generic API service as malware. Really goes to show ya how poor these malware lists are =/

**Comment by rdegges** [comment]
I just tweeted @malwarebytes: https://twitter.com/rdegges/status/933394889387077633

It's pretty much impossible to get a hold of them any other way that I can see, so hopefully they respond and take care of it >.>

**Comment by SupornoChaudhury** [comment]
Zscaler is blocking the site too. 
![image](https://user-images.githubusercontent.com/85339011/219560805-6b070ca5-e997-4dbe-b27e-6ce17e6ed4dc.png)
