### ISSUE TITLE
Not Working for older Android version

### ISSUE THREAD

**Issue by rushiathare100** [rdegges/ipify-api#20]
Hi, 
   this Api https://api.ipify.org?format=json is not working for older version of android but it is working fine in android marshmallow devices. 
    It is working fine after remove s from the API means APi URL is
 http://api.ipify.org?format=json

**Comment by rdegges** [comment]
It sounds like your mobile provider is intercepting your HTTPS traffic and trying to man-in-the-middle your connection. This isn't an ipify problem, it will be a problem for you with any HTTPS website that is secure. There's nothing I can do about this, sorry!

**Comment by rdegges** [comment]
You may also want to consider using a VPN since it looks like your internet traffic is being monitored.

**Comment by rushiathare100** [comment]
I got this error .
error: javax.net.ssl.SSLHandshakeException:
java.security.cert.CertPathValidatorException: Trust anchor for
certification path not found.

I think issue with SSL certificate u change that for lower android versions

**Comment by rdegges** [comment]
The SSL cert is valid / current and has not been changed recently. Usually SSL issues like you're seeing mean someone is trying to MITM your connection...
