### ISSUE TITLE
Api is logging user information

### ISSUE THREAD

**Issue by einacio** [rdegges/ipify-api#22]
On www.ipify.org it says

`No visitor information is ever logged. Period. `

however, the code has this line 

`fmt.Fprintln(os.Stderr, "WOOT:", r.Header.Get("X-Forwarded-For"))`

which on heroku effectively logs every request made to the api.
Is this code a misplaced debug or is the website incorrect?

**Comment by rdegges** [comment]
This was a misplaced debug, sorry :*( Was testing this out locally when trying to migrate to a new host. Depending on where this is hosted, the headers/method of retrieving the IP is different.

**Comment by rdegges** [comment]
Thanks for the contribution!
