### ISSUE TITLE
Cisco Security have blocked api.ipify.org using DNS RPZ

### ISSUE THREAD

**Issue by siddhuwarrier** [rdegges/ipify-api#31]
I was just using an application that was using your API (pretty cool idea, btw), and I noticed that it was failing because Cisco Security have blocked https://api.ipify.org using DNS RPZ. Specifically, 

```
A hostname, network address, or nameserver associated with api.ipify.org has been manually identified by CSIRT as malicious or a security risk which has resulted in this block.
```

I'm a little surprised this has happened as you state you're served by Heroku, but I thought you may want to look into this.

More details on DNS RPZ here: https://blogs.cisco.com/security/using-dns-rpz-to-block-malicious-dns-requests

HTH :)

TBF, looking at #2 , I can't help but think that this is part of the same problem. :( But interestingly, it means that a web service that is (imo incorrectly) using api.ipify.org is completely broken for as long as I have Umbrella screening my DNS requests.

**Comment by rdegges** [comment]
Unfortunately, there isn't much I can do in these cases. This is a perfect example of a company not thoroughly investigating an issue before messing things up =p

There are an infinite amount of "anti-virus" vendors, firewalls, etc., and all of them are self-governed -- this makes it nearly impossible for me to figure out who is blocking ipify, and how to get it removed.

If you know of a good way to submit ipify for manual review to someone who has the power to unblock it, that'd be awesome. I just spent a while googling around, however, and wasn't able to find anything =/
