### ISSUE TITLE
Your current data: {"ip": "<nil>"}

### ISSUE THREAD

**Issue by rdebath** [rdegges/ipify-api#4]
The api URL seems to be giving me a text result of:
`<nil>`
from the command
`wget http://api.ipify.org -4 -q -O -`

As json `curl 'http://api.ipify.org?format=json'` gives `{"ip":"\u003cnil\u003e"}`

If I were to guess I'd say it might be something to do with a header I add ... `X-Forwarded-for 192.0.2.1` but that's not certain.

**Comment by rdegges** [comment]
Fixed this just now -- it was an issue with the X-Forwarded-For header parsing stuff.

Previously I was grabbing the last IP address in the list -- but this is INCORRECT. The origin IP is the FIRST IP address.

This has been patched / released and is now working. =)

Thanks for the report!
