### ISSUE TITLE
Results of http and https are different.

### ISSUE THREAD

**Issue by saintevil** [rdegges/ipify-api#44]
Results of http and https are different.
I connected using mobile phone tethering.

`
$ curl https://api.ipify.org?format=json
{"ip":"223.62.22.15"}

$ curl http://api.ipify.org?format=json
{"ip":"223.39.189.45"}
`

**Comment by NiKiZe** [comment]
You might be behind CGNAT which could give you a different outgoing IP on each request.
It is also possible that there is transparent proxys on the http path.

**Comment by saintevil** [comment]
thanks
