### ISSUE TITLE
SSL settings

### ISSUE THREAD

**Issue by szepeviktor** [rdegges/ipify-api#7]
Please consider removing RC4 support etc.
https://www.ssllabs.com/ssltest/analyze.html?d=api.ipify.org&s=107.21.241.89&latest

See this fine tool:
https://mozilla.github.io/server-side-tls/ssl-config-generator/

**Comment by szepeviktor** [comment]
And in couple of days your cert expires.

**Comment by rdegges** [comment]
I'm currently working on migrating this project over to a new host (off Heroku), due to poor IPv6 support. When it is fully moved, I'll be passing the A+ ssllabs test =) Also: no worries about the cert -- I have auto-renewal / etc. configured.

**Comment by szepeviktor** [comment]
OVH is a huge hosting company: https://www.ovh.ie/vps/vps-cloud.xml (only in Canda)
faster instances: https://www.ovh.ie/cloud/instances/cpu.xml

**Comment by rdegges** [comment]
I'm currently evaluating digital ocean, but I'll check them out!

**Comment by szepeviktor** [comment]
If you go so "low" as DO, then check out [Vultr](http://www.vultr.com/?ref=6815796)
See the speedtest results: https://github.com/szepeviktor/wordpress-speedtest

**Comment by rdegges** [comment]
Will check it out! I guess you aren't a fan of DO? heh

**Comment by szepeviktor** [comment]
It's execution time is 60% higher, see the repo above.
