### ISSUE TITLE
Error status: -1

### ISSUE THREAD

**Issue by DiV666** [rdegges/ipify-api#9]
Hi, first off, thanks for this service!

For 2 days, some web clients have this error:

```
{
    "data": null,
    "status": -1,
    "config": {
        "method": "GET",
        "transformRequest": [null],
        "transformResponse": [null],
        "url": "https://api.ipify.org?format=json",
        "headers": {
            "Accept": "application/json, text/plain, */*"
        }
    },
    "statusText": ""
}
```

Could you tell me why?

Thank you very much.

**Comment by rdegges** [comment]
I'm not sure where that is coming from, but it definitely isn't from ipify? Have you changed your code sometime recently? We don't return this data.

**Comment by DiV666** [comment]
Hi, sorry, you're right, the error is caused by the angular http service.

I think the reason is because some software (antivirus, firewall...) is blocking the request to ipify as the HTTP error is -1

Sorry and thank you
